version: '3.9'

services:
  projeto-php:
    build: ./docker/php
    container_name: projeto-php
    privileged: true
    volumes: 
      - ./:/var/www/
    command: sh -c 'composer install && php bin/server.php'
    ports:
      - '9504:9504'
    depends_on: 
      - projeto-db
    working_dir: /var/www
  
  projeto-db:
    image: mysql:8.2.0
    container_name: projeto-db
    restart: always
    privileged: true
    environment:
      MYSQL_DATABASE: 'articlesTable'
      MYSQL_USER: 'mateus'
      MYSQL_PASSWORD: 'Mm@#91284025'
      MYSQL_ROOT_PASSWORD: 'Mm@#91284025'
    ports:
      - '3306:3306'
    volumes: 
      - ./storage/db/:/var/lib/mysql 


    